/**
 * PharmaConnect Global v3 — Full 15 partners from original
 */

export const PARTNERS_DATA = [
  {
    id: 'jnj',
    name: 'Johnson & Johnson',
    short: 'J&J',
    logo: '🏥',
    color: '#D51920',
    country: 'United States',
    region: 'North America',
    flag: '🇺🇸',
    hq: 'New Brunswick, NJ',
    revenue: '$89B',
    marketCap: '$394B+',
    ticker: 'NYSE: JNJ',
    focus: ['Oncology', 'Immunology', 'Neuroscience', 'MedTech'],
    rdBudget: '$17B/yr',
    products: [
      { name: 'Darzalex', area: 'Oncology', sales: '$11.7B', growth: '+20%', status: 'Top Seller', hot: true },
      { name: 'Tremfya', area: 'Immunology', sales: '$3.7B', growth: '+31%', status: 'Rising Star', hot: true },
      { name: 'Carvykti', area: 'Oncology', sales: '$900M+', growth: '+87%', status: 'High Growth', hot: true },
      { name: 'Spravato', area: 'Neuroscience', sales: '$1B+', growth: '+60%', status: 'Fast Growing', hot: true },
    ],
    contacts: [
      { name: 'Joaquin Duato', title: 'Chairman & CEO', dept: 'Executive', email: 'investor-relations@jnj.com' },
      { name: 'Bill Hait', title: 'VP External Innovation', dept: 'BD', email: 'investor-relations@jnj.com' },
    ],
    collabAreas: ['Oncology', 'CAR-T therapy', 'Neuroscience R&D', 'Clinical trials MENA/Africa'],
    bdApproach: 'Contact via jnjinnovation.com. JLABS partnership portal. BD team at ASCO, ASH, ESMO conferences.',
  },
  {
    id: 'lilly',
    name: 'Eli Lilly',
    short: 'Lilly',
    logo: '💊',
    color: '#C8102E',
    country: 'United States',
    region: 'North America',
    flag: '🇺🇸',
    hq: 'Indianapolis, IN',
    revenue: '$65.2B',
    marketCap: '$780B+',
    ticker: 'NYSE: LLY',
    focus: ['Cardiometabolic', 'Oncology', 'Neuroscience', 'Immunology'],
    rdBudget: '$11B+/yr',
    products: [
      { name: 'Mounjaro', area: 'Cardiometabolic', sales: '$11.5B+', growth: '+100%+', status: 'Mega Blockbuster', hot: true },
      { name: 'Zepbound', area: 'Obesity', sales: '$6B+', growth: 'Rapid', status: 'Mega Blockbuster', hot: true },
      { name: 'Verzenio', area: 'Oncology', sales: '$4.5B+', growth: '+20%', status: 'Blockbuster', hot: true },
    ],
    contacts: [
      { name: 'David Ricks', title: 'Chairman & CEO', dept: 'Executive', email: 'investor@lilly.com' },
      { name: 'Daniel Skovronsky', title: 'Chief Scientific Officer', dept: 'R&D', email: 'investor@lilly.com' },
    ],
    collabAreas: ['GLP-1 therapies', 'Obesity', "Alzheimer's R&D", 'Manufacturing partnerships'],
    bdApproach: 'Submit via partnering.lilly.com. Focus on novel mechanisms. Manufacturing partnerships for GLP-1 supply.',
  },
  {
    id: 'novartis',
    name: 'Novartis',
    short: 'Novartis',
    logo: '💎',
    color: '#0460A9',
    country: 'Switzerland',
    region: 'Europe',
    flag: '🇨🇭',
    hq: 'Basel, Switzerland',
    revenue: '$50.3B',
    marketCap: '$230B+',
    ticker: 'SIX: NOVN',
    focus: ['Cardiovascular', 'Oncology', 'Immunology', 'Neuroscience'],
    rdBudget: '$9.8B/yr',
    products: [
      { name: 'Entresto', area: 'Cardiovascular', sales: '$7.2B', growth: '+11%', status: 'Blockbuster', hot: true },
      { name: 'Kisqali', area: 'Oncology', sales: '$4.4B', growth: '+52%', status: 'High Growth', hot: true },
      { name: 'Pluvicto', area: 'Oncology', sales: '$1.4B', growth: '+40%', status: 'Fast Growing', hot: true },
    ],
    contacts: [{ name: 'Vas Narasimhan', title: 'CEO', dept: 'Executive', email: 'investor.relations@novartis.com' }],
    collabAreas: ['Radioligand therapy', 'Gene therapy', 'Cardiovascular'],
    bdApproach: 'novartis.com/partnering. Novartis Venture Fund for early-stage.',
  },
  {
    id: 'roche',
    name: 'Roche',
    short: 'Roche',
    logo: '🧪',
    color: '#0066CC',
    country: 'Switzerland',
    region: 'Europe',
    flag: '🇨🇭',
    hq: 'Basel, Switzerland',
    revenue: '$60.5B',
    marketCap: '$240B+',
    ticker: 'SIX: ROG',
    focus: ['Oncology', 'Neuroscience', 'Ophthalmology', 'Diagnostics'],
    rdBudget: '$14B+/yr',
    products: [
      { name: 'Vabysmo', area: 'Ophthalmology', sales: '$4.5B', growth: '+65%', status: 'High Growth', hot: true },
      { name: 'Ocrevus', area: 'Neuroscience', sales: '$7.3B', growth: '+8%', status: 'Blockbuster', hot: true },
      { name: 'Hemlibra', area: 'Hematology', sales: '$4.2B', growth: '+12%', status: 'Blockbuster', hot: true },
    ],
    contacts: [{ name: 'Thomas Schinecker', title: 'CEO', dept: 'Executive', email: 'investor.relations@roche.com' }],
    collabAreas: ['Oncology novel targets', 'Companion diagnostics', 'Personalized medicine'],
    bdApproach: 'partnering.roche.com. Genentech portal for US.',
  },
  {
    id: 'pfizer',
    name: 'Pfizer',
    short: 'Pfizer',
    logo: '💙',
    color: '#0093D0',
    country: 'United States',
    region: 'North America',
    flag: '🇺🇸',
    hq: 'New York, NY',
    revenue: '$59.5B',
    marketCap: '$145B',
    ticker: 'NYSE: PFE',
    focus: ['Oncology', 'Vaccines', 'Anti-infectives', 'Rare Disease'],
    rdBudget: '$10.5B/yr',
    products: [
      { name: 'Eliquis', area: 'Cardiovascular', sales: '$12.1B', growth: '+5%', status: 'Top Seller', hot: true },
      { name: 'Padcev', area: 'Oncology', sales: '$2.8B', growth: '+100%+', status: 'High Growth', hot: true },
      { name: 'Prevnar', area: 'Vaccines', sales: '$6.4B', growth: '+3%', status: 'Blockbuster', hot: true },
    ],
    contacts: [{ name: 'Albert Bourla', title: 'Chairman & CEO', dept: 'Executive', email: 'investor.relations@pfizer.com' }],
    collabAreas: ['ADC development', 'Vaccine development', 'Rare disease', 'Gene therapy'],
    bdApproach: 'pfizer.com/partnering. Pfizer Ventures for early stage. Very active BD ($43B Seagen).',
  },
  {
    id: 'sanofi',
    name: 'Sanofi',
    short: 'Sanofi',
    logo: '🔬',
    color: '#7B2D8E',
    country: 'France',
    region: 'Europe',
    flag: '🇫🇷',
    hq: 'Paris, France',
    revenue: '$46.1B',
    marketCap: '$130B+',
    ticker: 'EURONEXT: SAN',
    focus: ['Immunology', 'Rare Disease', 'Vaccines', 'Oncology'],
    rdBudget: '$7.5B/yr',
    products: [
      { name: 'Dupixent', area: 'Immunology', sales: '$13.1B', growth: '+23%', status: 'Mega Blockbuster', hot: true },
      { name: 'Beyfortus', area: 'Vaccines', sales: '$1.8B', growth: 'New', status: 'New Launch', hot: true },
    ],
    contacts: [{ name: 'Paul Hudson', title: 'CEO', dept: 'Executive', email: 'investor.relations@sanofi.com' }],
    collabAreas: ['Immunology', 'Rare disease', 'Vaccines', 'Manufacturing MENA/Africa'],
    bdApproach: 'sanofi.com/partnering. Has offices in ALGERIA — direct connection. Sanofi Pasteur for vaccines.',
  },
  {
    id: 'astrazeneca',
    name: 'AstraZeneca',
    short: 'AZ',
    logo: '🌐',
    color: '#830051',
    country: 'UK/Sweden',
    region: 'Europe',
    flag: '🇬🇧',
    hq: 'Cambridge, UK',
    revenue: '$54.1B',
    marketCap: '$220B+',
    ticker: 'LSE: AZN',
    focus: ['Oncology', 'CVRM', 'Respiratory', 'Rare Disease'],
    rdBudget: '$11.1B/yr',
    products: [
      { name: 'Farxiga', area: 'CVRM', sales: '$7.1B', growth: '+22%', status: 'Mega Blockbuster', hot: true },
      { name: 'Enhertu', area: 'Oncology', sales: '$4.8B', growth: '+36%', status: 'High Growth', hot: true },
    ],
    contacts: [{ name: 'Pascal Soriot', title: 'CEO', dept: 'Executive', email: 'investor.relations@astrazeneca.com' }],
    collabAreas: ['ADC development', 'CVRM', 'Emerging markets trials'],
    bdApproach: 'astrazeneca.com/partnering. Strong emerging markets presence.',
  },
  {
    id: 'gsk',
    name: 'GSK',
    short: 'GSK',
    logo: '🧫',
    color: '#F36633',
    country: 'United Kingdom',
    region: 'Europe',
    flag: '🇬🇧',
    hq: 'London, UK',
    revenue: '$38.4B',
    marketCap: '$80B+',
    ticker: 'LSE: GSK',
    focus: ['HIV', 'Vaccines', 'Respiratory', 'Oncology'],
    rdBudget: '$7B+/yr',
    products: [
      { name: 'Shingrix', area: 'Vaccines', sales: '$3.2B', growth: '-8%', status: 'Blockbuster', hot: true },
      { name: 'Arexvy', area: 'Vaccines', sales: '$1.7B', growth: 'New', status: 'New Launch', hot: true },
    ],
    contacts: [{ name: 'Emma Walmsley', title: 'CEO', dept: 'Executive', email: 'investor.relations@gsk.com' }],
    collabAreas: ['Vaccines', 'HIV', 'Respiratory', 'Africa manufacturing'],
    bdApproach: 'gsk.com/partnering. ViiV for HIV. Strong Africa presence.',
  },
  {
    id: 'bayer',
    name: 'Bayer',
    short: 'Bayer',
    logo: '⚗️',
    color: '#10857F',
    country: 'Germany',
    region: 'Europe',
    flag: '🇩🇪',
    hq: 'Leverkusen',
    revenue: '$50.7B',
    marketCap: '$25B+',
    ticker: 'XETRA: BAYN',
    focus: ['Cardiovascular', 'Oncology', 'Cell & Gene Therapy'],
    rdBudget: '$6B+/yr',
    products: [
      { name: 'Nubeqa', area: 'Oncology', sales: '$2.4B', growth: '+40%', status: 'High Growth', hot: true },
      { name: 'Kerendia', area: 'Cardiovascular', sales: '$750M', growth: '+90%', status: 'Fast Growing', hot: true },
    ],
    contacts: [{ name: 'Bill Anderson', title: 'CEO', dept: 'Executive', email: 'investor.relations@bayer.com' }],
    collabAreas: ['Cell & gene therapy', 'Cardiovascular', 'MENA partnerships'],
    bdApproach: 'bayer.com/partnering. Leaps by Bayer for innovation.',
  },
  {
    id: 'sinovac',
    name: 'Sinovac',
    short: 'Sinovac',
    logo: '🧬',
    color: '#0066CC',
    country: 'China',
    region: 'Asia-Pacific',
    flag: '🇨🇳',
    hq: 'Beijing, China',
    revenue: '$429M',
    marketCap: '$460M',
    ticker: 'NASDAQ: SVA',
    focus: ['Vaccines', 'Infectious Disease'],
    rdBudget: 'Undisclosed',
    products: [
      { name: 'CoronaVac', area: 'Vaccines', sales: '60+ countries', growth: 'Post-pandemic', status: 'Flagship', hot: true },
      { name: 'Healive', area: 'Vaccines', sales: 'WHO PQ', growth: 'Stable', status: 'Established', hot: true },
    ],
    contacts: [{ name: 'Weidong Yin', title: 'President & CEO', dept: 'Executive', email: 'ir@sinovac.com' }],
    collabAreas: ['Vaccine tech transfer', 'Manufacturing JV', 'WHO PQ'],
    bdApproach: 'ir@sinovac.com. Good for vaccine tech transfer. Colombia JV model.',
  },
  {
    id: '3sbio',
    name: '3SBio',
    short: '3SBio',
    logo: '🔬',
    color: '#00875A',
    country: 'China',
    region: 'Asia-Pacific',
    flag: '🇨🇳',
    hq: 'Shenyang, China',
    revenue: '$1.26B',
    marketCap: '$7.1B HKD',
    ticker: 'HKEX: 01530',
    focus: ['Oncology', 'Nephrology', 'Auto-immune'],
    rdBudget: '20+ candidates',
    products: [
      { name: 'SSGJ-707', area: 'Oncology', sales: '$6B Pfizer deal', growth: 'Milestone', status: 'Pfizer $6B Deal', hot: true },
      { name: 'Yisaipu', area: 'Auto-immune', sales: '60%+ China share', growth: 'Leader', status: 'Blockbuster', hot: true },
    ],
    contacts: [{ name: 'Tom Folinsbee', title: 'Director BD', dept: 'BD', email: 'tomfolinsbee@3sbio.com' }],
    collabAreas: ['Bispecific antibodies', 'Biosimilar manufacturing', 'CDMO services'],
    bdApproach: 'Contact Tom Folinsbee. Open to licensing (Pfizer $6B deal). CDMO capabilities.',
  },
  {
    id: 'hikma',
    name: 'Hikma Pharmaceuticals',
    short: 'Hikma',
    logo: '🇯🇴',
    color: '#003366',
    country: 'Jordan',
    region: 'MENA',
    flag: '🇯🇴',
    hq: 'Amman, Jordan',
    revenue: '$2.9B',
    marketCap: '$5B+',
    ticker: 'LSE: HIK',
    focus: ['Generics', 'Injectables', 'Branded'],
    rdBudget: '$200M+/yr',
    products: [
      { name: 'Generic Injectables', area: 'Injectables', sales: '$1B+', growth: '+8%', status: 'Blockbuster', hot: true },
      { name: 'Branded Portfolio', area: 'MENA Brands', sales: '$700M', growth: '+12%', status: 'Strong Growth', hot: true },
    ],
    contacts: [{ name: 'Said Darwazah', title: 'CEO', dept: 'Executive', email: 'investor.relations@hikma.com' }],
    collabAreas: ['MENA distribution', 'Generic manufacturing', 'Injectable partnerships', 'North Africa expansion'],
    bdApproach: 'hikma.com/partnering. BEST partner for MENA market entry. Has existing Algeria operations.',
  },
  {
    id: 'biocon',
    name: 'Biocon Biologics',
    short: 'Biocon',
    logo: '🇮🇳',
    color: '#1B5E20',
    country: 'India',
    region: 'Asia-Pacific',
    flag: '🇮🇳',
    hq: 'Bangalore, India',
    revenue: '$1.5B+',
    marketCap: '$5B+',
    ticker: 'BSE: BIOCON',
    focus: ['Biosimilars', 'Insulins', 'Oncology'],
    rdBudget: '$300M+/yr',
    products: [
      { name: 'Insulin Glargine', area: 'Diabetes', sales: 'Global leader', growth: 'Growing', status: 'Blockbuster', hot: true },
      { name: 'Trastuzumab', area: 'Oncology', sales: 'Global', growth: 'Stable', status: 'Established', hot: true },
    ],
    contacts: [{ name: 'Kiran Mazumdar-Shaw', title: 'Chairperson', dept: 'Executive', email: 'investor.relations@biocon.com' }],
    collabAreas: ['Biosimilar development', 'Manufacturing partnerships', 'Emerging market access'],
    bdApproach: 'biocon.com. Excellent for biosimilar partnerships. WHO PQ track record.',
  },
  {
    id: 'julphar',
    name: 'Julphar',
    short: 'Julphar',
    logo: '🇦🇪',
    color: '#00529B',
    country: 'UAE',
    region: 'MENA',
    flag: '🇦🇪',
    hq: 'Ras Al Khaimah, UAE',
    revenue: '$500M+',
    marketCap: 'Private',
    ticker: 'DFM: JULPHAR',
    focus: ['Generics', 'Biosimilars', 'OTC'],
    rdBudget: 'Growing',
    products: [{ name: 'Generic Portfolio', area: 'Generics', sales: '100+ products', growth: 'Growing', status: 'Growing', hot: true }],
    contacts: [{ name: 'Corporate Development', title: 'BD Team', dept: 'BD', email: 'info@julphar.net' }],
    collabAreas: ['MENA co-marketing', 'Generic licensing', 'OTC distribution', 'Gulf market access'],
    bdApproach: 'Direct contact via julphar.net. Good for GCC market access.',
  },
  {
    id: 'spimaco',
    name: 'SPIMACO',
    short: 'SPIMACO',
    logo: '🇸🇦',
    color: '#006C35',
    country: 'Saudi Arabia',
    region: 'MENA',
    flag: '🇸🇦',
    hq: 'Riyadh, Saudi Arabia',
    revenue: '$800M+',
    marketCap: 'SAR 8B+',
    ticker: 'Tadawul: 2070',
    focus: ['Generics', 'OTC', 'Branded'],
    rdBudget: 'Growing',
    products: [{ name: 'Generic Portfolio', area: 'Generics', sales: 'Saudi leader', growth: 'Growing', status: 'Established', hot: true }],
    contacts: [{ name: 'Corporate Development', title: 'BD Team', dept: 'BD', email: 'info@spimaco.com.sa' }],
    collabAreas: ['Saudi market access', 'Local manufacturing', 'NUPCO tenders', 'Vision 2030 JV'],
    bdApproach: 'Direct to BD team. Vision 2030 incentives for JV manufacturing in Saudi.',
  },
]
