/**
 * PharmaConnect Global v3 — Full 28 regulatory agencies from original
 */

export const AGENCIES_DATA = [
  {
    id: 'fda',
    name: 'FDA',
    country: 'United States',
    flag: '🇺🇸',
    color: '#2563EB',
    region: 'Americas',
    fullName: 'Food and Drug Administration',
    avgApproval: '10-12 mo',
    cost: '$2.8M+',
    difficulty: 5,
    marketSize: '$605B',
    steps: [
      { phase: 'Pre-IND', title: 'Pre-IND Meeting', dur: '3-6 mo', docs: ['Drug Master File', 'CMC', 'Preclinical reports', 'Tox data', 'Protocol'], tips: 'Request Type B meeting. FDA responds in 60 days. Critical for foreign manufacturers.' },
      { phase: 'IND', title: 'IND Application', dur: '30-day', docs: ['Form 1571', "Investigator's Brochure", 'Protocol', 'CMC', 'Pharm/Tox summary'], tips: 'Effective after 30 days unless hold. Begin trials if no hold.' },
      { phase: 'Phase I-III', title: 'Clinical Trials', dur: '3-6 yrs', docs: ['IRB approval', 'GCP compliance', 'DMC reports', 'IND annual reports', 'SAP'], tips: 'Ph I: 20-80 (safety). Ph II: 100-300 (efficacy). Ph III: 1,000-5,000+ (pivotal). End-of-Ph II meeting critical.' },
      { phase: 'NDA/BLA', title: 'NDA/BLA Submission', dur: '10-12 mo review', docs: ['eCTD Modules 1-5', 'PDUFA fee $2.8M', 'Labeling', 'REMS'], tips: 'eCTD format required. Priority review 6-8 mo. AdCom possible.' },
      { phase: 'Post-Market', title: 'Approval & Launch', dur: 'Ongoing', docs: ['Phase IV', 'MedWatch', 'Annual reports'], tips: 'US Agent required. Register establishment. cGMP inspections.' },
    ],
    keyContacts: [
      { name: 'CDER', role: 'Drug review', how: 'FDA ESG gateway' },
      { name: 'Office of International Programs', role: 'Foreign liaison', how: 'internationalquestions@fda.hhs.gov' },
    ],
    foreignTips: 'Algeria→US: Register establishment, US Agent, cGMP (FDA inspects Algeria), English label, US importer. Consider 505(b)(2) for modified generics.',
  },
  {
    id: 'hc',
    name: 'Health Canada',
    country: 'Canada',
    flag: '🇨🇦',
    color: '#FF0000',
    region: 'Americas',
    fullName: 'Health Products & Food Branch',
    avgApproval: '12 mo',
    cost: 'CAD $400K+',
    difficulty: 3,
    marketSize: '$35B',
    steps: [
      { phase: 'CTA', title: 'Clinical Trial Application', dur: '30 days', docs: ['CTA form', 'Protocol', 'GCP docs'], tips: '30-day default approval.' },
      { phase: 'NDS', title: 'New Drug Submission', dur: '300 days', docs: ['eCTD', 'Product Monograph'], tips: 'Project Orbis for oncology. Priority for serious conditions.' },
      { phase: 'Market', title: 'Market Access', dur: '3-6 mo', docs: ['CADTH HTA', 'Provincial formulary'], tips: 'CADTH + pCPA for real access.' },
    ],
    keyContacts: [{ name: 'BGTD', role: 'Drug review', how: 'eCTD gateway' }],
    foreignTips: 'Bilingual EN/FR labeling. Drug Establishment License. Good US stepping stone.',
  },
  {
    id: 'anvisa',
    name: 'ANVISA',
    country: 'Brazil',
    flag: '🇧🇷',
    color: '#009739',
    region: 'Americas',
    fullName: 'Agência Nacional de Vigilância Sanitária',
    avgApproval: '12-24 mo',
    cost: 'Variable',
    difficulty: 3,
    marketSize: '$40B',
    steps: [
      { phase: 'GMP', title: 'GMP Certification (CBPF)', dur: '6-12 mo', docs: ['GMP request', 'Manufacturing dossier'], tips: 'MUST inspect foreign sites BEFORE registration.' },
      { phase: 'Reg', title: 'Registration', dur: '365 days / 120 priority', docs: ['CTD', 'Zone IVb stability', 'BR labeling'], tips: 'Reliance on WHO PQ/FDA/EMA.' },
      { phase: 'Price', title: 'CMED Pricing', dur: '1-3 mo', docs: ['CMED submission', 'CONITEC HTA'], tips: 'Large SUS public procurement.' },
    ],
    keyContacts: [{ name: 'GGMED', role: 'Drug registration', how: 'ANVISA portal' }],
    foreignTips: 'Brazilian representative required. Zone IVb stability. Portuguese labeling.',
  },
  {
    id: 'ema',
    name: 'EMA',
    country: 'European Union',
    flag: '🇪🇺',
    color: '#003399',
    region: 'Europe',
    fullName: 'European Medicines Agency',
    avgApproval: '12-15 mo',
    cost: '€300K+',
    difficulty: 5,
    marketSize: '$310B',
    steps: [
      { phase: 'Advice', title: 'Scientific Advice & PIP', dur: '2-3 mo', docs: ['SA request', 'Development plan', 'PIP'], tips: 'Reduced fees for SMEs. PIP mandatory.' },
      { phase: 'MAA', title: 'Marketing Authorisation', dur: '210 days', docs: ['eCTD', 'EU Module 1', 'RMP', 'ERA'], tips: 'Centralized = valid 27+3 states. Letter of Intent 7 months before.' },
      { phase: 'CHMP', title: 'Assessment & Decision', dur: '210 days + stops', docs: ['LoQ responses', 'GMP certs', 'Updated RMP'], tips: 'Day 120: List of Questions. Day 210: CHMP Opinion. EC Decision in 67 days.' },
    ],
    keyContacts: [
      { name: 'CHMP', role: 'Evaluation', how: 'EMA portal' },
      { name: 'SME Office', role: 'Small companies', how: 'smeoffice@ema.europa.eu' },
    ],
    foreignTips: 'Need EU-based MAH, QP for batch release, EU QPPV. Consider EU subsidiary.',
  },
  {
    id: 'mhra',
    name: 'MHRA',
    country: 'United Kingdom',
    flag: '🇬🇧',
    color: '#012169',
    region: 'Europe',
    fullName: 'Medicines & Healthcare products Regulatory Agency',
    avgApproval: '8-12 mo',
    cost: '£100-300K',
    difficulty: 3,
    marketSize: '$45B',
    steps: [
      { phase: 'ILAP', title: 'Innovation Passport', dur: 'Ongoing', docs: ['ILAP application', 'TDP'], tips: 'Post-Brexit accelerated pathway.' },
      { phase: 'MAA', title: 'Marketing Authorisation', dur: '210 days std', docs: ['CTD', 'UK Module 1', 'SmPC', 'RMP'], tips: 'Reliance on EMA/FDA. International Recognition Framework.' },
      { phase: 'NICE', title: 'HTA & NHS Access', dur: '3-6 mo', docs: ['NICE submission', 'Health economics'], tips: 'NICE/SMC for NHS funding.' },
    ],
    keyContacts: [{ name: 'MHRA Licensing', role: 'Authorisation', how: 'MHRA portal' }],
    foreignTips: 'UK Responsible Person needed. English labeling. Post-Brexit opportunities.',
  },
  {
    id: 'bfarm',
    name: 'BfArM',
    country: 'Germany',
    flag: '🇩🇪',
    color: '#DD0000',
    region: 'Europe',
    fullName: 'Federal Institute for Drugs and Medical Devices',
    avgApproval: 'Varies (national or MRP)',
    cost: '€50-150K',
    difficulty: 3,
    marketSize: '$65B',
    steps: [
      { phase: 'National', title: 'National / MRP / DCP', dur: '210 days', docs: ['CTD', 'German SmPC', 'PIL'], tips: 'Germany is often Reference Member State for MRP/DCP.' },
      { phase: 'G-BA', title: 'G-BA Benefit Assessment', dur: '6 mo', docs: ['Dossier', 'AMNOG assessment'], tips: 'AMNOG assessment determines pricing.' },
    ],
    keyContacts: [{ name: 'BfArM', role: 'National authority', how: 'bfarm.de' }],
    foreignTips: 'Largest EU market by volume. AMNOG pricing is strict but market is huge.',
  },
  {
    id: 'ansm',
    name: 'ANSM',
    country: 'France',
    flag: '🇫🇷',
    color: '#002395',
    region: 'Europe',
    fullName: 'Agence Nationale de Sécurité du Médicament',
    avgApproval: 'Varies',
    cost: '€30-100K',
    difficulty: 3,
    marketSize: '$45B',
    steps: [
      { phase: 'AMM', title: 'Marketing Authorisation', dur: '210 days national', docs: ['CTD', 'French SmPC', 'PIL FR'], tips: 'Can be national or via MRP/DCP. Strong biosimilar uptake.' },
      { phase: 'HAS', title: 'HAS/CEPS Assessment', dur: '3-6 mo', docs: ['HAS transparency dossier', 'CEPS negotiation'], tips: 'HAS SMR/ASMR rating determines reimbursement and price.' },
    ],
    keyContacts: [{ name: 'ANSM', role: 'National authority', how: 'ansm.sante.fr' }],
    foreignTips: 'French labeling required. Francophone connection with Algeria is an advantage. Strong generics market.',
  },
  {
    id: 'aifa',
    name: 'AIFA',
    country: 'Italy',
    flag: '🇮🇹',
    color: '#009246',
    region: 'Europe',
    fullName: 'Agenzia Italiana del Farmaco',
    avgApproval: 'Varies',
    cost: '€30-80K',
    difficulty: 3,
    marketSize: '$38B',
    steps: [
      { phase: 'AIC', title: 'Marketing Authorisation', dur: '210 days', docs: ['CTD', 'Italian SmPC/PIL'], tips: 'National, MRP or DCP. Italy often Co-RMS.' },
      { phase: 'AIFA', title: 'P&R Negotiation', dur: '3-12 mo', docs: ['Pharmacoeconomic dossier'], tips: 'AIFA negotiates price. Class A (reimbursed) vs Class C.' },
    ],
    keyContacts: [{ name: 'AIFA', role: 'National authority', how: 'aifa.gov.it' }],
    foreignTips: 'Third largest EU market. Good generics opportunities.',
  },
  {
    id: 'nmpa',
    name: 'NMPA',
    country: 'China',
    flag: '🇨🇳',
    color: '#DE2910',
    region: 'Asia-Pacific',
    fullName: 'National Medical Products Administration',
    avgApproval: '12-18 mo',
    cost: '¥500K-2M+',
    difficulty: 4,
    marketSize: '$175B',
    steps: [
      { phase: 'CDE', title: 'CDE Consultation', dur: '1-2 mo', docs: ['Development summary', 'CMC overview'], tips: 'China joined ICH — accepts international data now.' },
      { phase: 'CTA', title: 'Clinical Trial Application', dur: '60-day default', docs: ['CTD application', 'Protocol', 'IB'], tips: '60-day default (2018 reform). Global MRCT accepted with Chinese patients.' },
      { phase: 'NDA', title: 'NDA & Review', dur: '200 working days', docs: ['CTD NDA', 'Chinese data', 'GMP cert'], tips: 'Priority for innovative/pediatric/rare disease. Conditional approval available.' },
      { phase: 'NRDL', title: 'NRDL & Market', dur: '3-6 mo', docs: ['Reimbursement application', 'Hospital listing'], tips: 'NRDL inclusion critical. Partner with local distributor.' },
    ],
    keyContacts: [
      { name: 'CDE', role: 'Drug evaluation', how: 'CDE e-submission' },
      { name: 'Local CROs', role: 'Trial management', how: 'WuXi, Tigermed' },
    ],
    foreignTips: 'Chinese agent required. Import Drug License. Chinese labeling. Partner with Chinese pharma.',
  },
  {
    id: 'pmda',
    name: 'PMDA',
    country: 'Japan',
    flag: '🇯🇵',
    color: '#BC002D',
    region: 'Asia-Pacific',
    fullName: 'Pharmaceuticals & Medical Devices Agency',
    avgApproval: '12 mo',
    cost: '¥10-50M',
    difficulty: 4,
    marketSize: '$95B',
    steps: [
      { phase: 'CTN', title: 'Clinical Trial Notification', dur: '30 days', docs: ['CTN', 'Protocol', 'IB', 'J-GCP'], tips: 'Bridging studies may be needed. SAKIGAKE for breakthroughs.' },
      { phase: 'J-NDA', title: 'J-NDA Submission', dur: '12 mo review', docs: ['CTD Japanese', 'Japanese PI', 'RMP', 'GMP cert'], tips: 'Priority (9 mo), SAKIGAKE (6 mo). NHI price listing critical.' },
    ],
    keyContacts: [{ name: 'PMDA', role: 'Drug evaluation', how: 'PMDA gateway' }],
    foreignTips: 'Japan-based MAH needed. NHI listing critical. Partner with Japanese pharma.',
  },
  {
    id: 'mfds',
    name: 'MFDS',
    country: 'South Korea',
    flag: '🇰🇷',
    color: '#0047A0',
    region: 'Asia-Pacific',
    fullName: 'Ministry of Food and Drug Safety',
    avgApproval: '12-18 mo',
    cost: '₩50-200M',
    difficulty: 4,
    marketSize: '$25B',
    steps: [
      { phase: 'IND', title: 'IND Application', dur: '30 days', docs: ['IND form', 'Protocol', 'CMC'], tips: 'Korean GCP required. Bridging studies possible.' },
      { phase: 'NDA', title: 'NDA & HIRA', dur: '12-18 mo', docs: ['CTD NDA', 'Korean PI', 'Cost-effectiveness'], tips: 'Priority for breakthrough. HIRA/NHIS for reimbursement.' },
    ],
    keyContacts: [{ name: 'MFDS', role: 'Drug review', how: 'MFDS portal' }],
    foreignTips: 'Korean agent needed. MFDS inspects foreign sites. NHI listing essential.',
  },
  {
    id: 'tga',
    name: 'TGA',
    country: 'Australia',
    flag: '🇦🇺',
    color: '#00843D',
    region: 'Asia-Pacific',
    fullName: 'Therapeutic Goods Administration',
    avgApproval: '8-11 mo',
    cost: 'AUD $200K+',
    difficulty: 3,
    marketSize: '$22B',
    steps: [
      { phase: 'CTN', title: 'Clinical Trial Notification', dur: 'Immediate', docs: ['CTN', 'Ethics approval'], tips: 'CTN is simple and fast. Popular for early-phase trials.' },
      { phase: 'Reg', title: 'Registration', dur: '255 working days', docs: ['CTD', 'Australian PI/CMI'], tips: 'Abbreviated evaluation for FDA/EMA-approved products. ACCESS Consortium.' },
      { phase: 'PBS', title: 'PBS Listing', dur: '3-6 mo', docs: ['PBAC submission', 'Economic evaluation'], tips: 'PBAC recommends PBS listing. Essential for market access.' },
    ],
    keyContacts: [{ name: 'TGA', role: 'Evaluation', how: 'TGA eBusiness' }],
    foreignTips: 'Australian Sponsor required. GMP clearance (PIC/S recognition). ACCESS work-sharing.',
  },
  {
    id: 'cdsco',
    name: 'CDSCO',
    country: 'India',
    flag: '🇮🇳',
    color: '#FF9933',
    region: 'Asia-Pacific',
    fullName: 'Central Drugs Standard Control Organisation',
    avgApproval: '12-18 mo',
    cost: 'Low',
    difficulty: 2,
    marketSize: '$50B',
    steps: [
      { phase: 'CT', title: 'Clinical Trial Permission', dur: '90 days', docs: ['Form 44', 'Protocol', 'IB', 'Ethics'], tips: 'Phase III waiver possible for globally approved drugs. New Drugs Rules 2019 reformed process.' },
      { phase: 'NDA', title: 'New Drug Application', dur: '12 mo', docs: ['CTD format', 'Indian trial data (if needed)', 'GMP cert'], tips: 'Accelerated for orphan, breakthrough. India accepts global data more now.' },
    ],
    keyContacts: [{ name: 'CDSCO', role: 'Drug regulation', how: 'cdsco.gov.in/sugam portal' }],
    foreignTips: 'Huge generic market. Low cost entry. Great for biosimilar partnerships. WHO PQ valued.',
  },
  {
    id: 'sfda',
    name: 'SFDA',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    color: '#006C35',
    region: 'MENA',
    fullName: 'Saudi Food & Drug Authority',
    avgApproval: '12-18 mo',
    cost: 'SAR 50-200K',
    difficulty: 3,
    marketSize: '$12B',
    steps: [
      { phase: 'Pre', title: 'Classification & Pre-submission', dur: '1-2 mo', docs: ['Product classification', 'Regulatory strategy', 'GMP certificate'], tips: 'SFDA has fast-track for essential medicines. Saudi Vision 2030 promotes local pharma manufacturing.' },
      { phase: 'Reg', title: 'Marketing Authorization', dur: '12-18 mo', docs: ['CTD format', 'GCC labeling', 'Stability (Zone IVa: 30°C/65% RH)', 'GMP cert (PIC/S or WHO)', 'CoA from country of origin'], tips: 'SFDA accepts reliance on FDA/EMA approvals for accelerated review. GCC Centralized Procedure available.' },
      { phase: 'Price', title: 'Pricing & Market', dur: '2-4 mo', docs: ['Price justification', 'Pharmacoeconomic data'], tips: 'SFDA sets reference pricing. Large government procurement via NUPCO. Private sector also significant.' },
    ],
    keyContacts: [
      { name: 'SFDA Drug Sector', role: 'Registration', how: 'sfda.gov.sa portal' },
      { name: 'NUPCO', role: 'Government procurement', how: 'nupco.com' },
    ],
    foreignTips: 'Algeria→Saudi: (1) Local authorized agent/distributor (LAA) MANDATORY, (2) GMP cert (PIC/S, WHO, or SFDA inspection), (3) Arabic + English labeling, (4) Zone IVa stability, (5) SFDA accepts FDA/EMA reliance, (6) Vision 2030 incentives for local manufacturing. EXCELLENT market — largest in MENA.',
  },
  {
    id: 'jfda',
    name: 'JFDA',
    country: 'Jordan',
    flag: '🇯🇴',
    color: '#007A3D',
    region: 'MENA',
    fullName: 'Jordan Food & Drug Administration',
    avgApproval: '6-12 mo',
    cost: 'JOD 5-20K',
    difficulty: 2,
    marketSize: '$2B',
    steps: [
      { phase: 'Pre', title: 'Pre-registration', dur: '1 mo', docs: ['Application form', 'CPP (Certificate of Pharmaceutical Product)', 'GMP cert'], tips: 'Jordan is a pharma HUB for MENA. Re-export to Iraq, Syria, Palestine, Libya. Very pharma-friendly regulatory environment.' },
      { phase: 'Reg', title: 'Registration', dur: '6-12 mo', docs: ['CTD dossier (eCTD accepted)', 'Stability (Zone IVa)', 'CoA', 'GMP cert', 'Samples for testing'], tips: 'JFDA is relatively fast. Mutual recognition with some Arab countries. Strong local generics industry (Hikma, Dar Al Dawa).' },
      { phase: 'Market', title: 'Market Entry', dur: '1-2 mo', docs: ['Pricing approval', 'Import license', 'Distribution agreement'], tips: 'Government tenders through JPD. Private market significant. Good gateway to Iraq & Levant markets.' },
    ],
    keyContacts: [
      { name: 'JFDA Drug Directorate', role: 'Registration', how: 'jfda.jo portal' },
      { name: 'JPD', role: 'Government procurement', how: 'jpd.com.jo' },
    ],
    foreignTips: 'Algeria→Jordan: (1) Local agent/distributor required, (2) GMP cert needed, (3) Arabic + English labeling, (4) CPP from Algeria required, (5) Jordan has FREE TRADE ZONES — excellent for re-export to Iraq, Syria, Palestine. Hikma & Dar Al Dawa are potential partners. Very accessible market.',
  },
  {
    id: 'mohap',
    name: 'MOH-UAE',
    country: 'UAE',
    flag: '🇦🇪',
    color: '#FF0000',
    region: 'MENA',
    fullName: 'Ministry of Health & Prevention + HAAD/DHA',
    avgApproval: '6-12 mo',
    cost: 'AED 20-100K',
    difficulty: 3,
    marketSize: '$6B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '6-12 mo', docs: ['CTD dossier', 'GMP cert', 'CPP', 'Stability Zone IVa/IVb', 'Legal agent docs'], tips: 'Multiple authorities: MOH (federal), HAAD (Abu Dhabi), DHA (Dubai). MOH registration usually sufficient. Fast-track for FDA/EMA approved.' },
      { phase: 'Market', title: 'Market Entry', dur: '1-2 mo', docs: ['Price approval', 'Import permit', 'Distribution agreement'], tips: 'Premium pricing possible. Large private sector. Medical tourism hub. Re-export to GCC.' },
    ],
    keyContacts: [
      { name: 'MOH Drug Department', role: 'Registration', how: 'mohap.gov.ae' },
      { name: 'DOH Abu Dhabi', role: 'Abu Dhabi registration', how: 'doh.gov.ae' },
    ],
    foreignTips: 'Local agent mandatory. Premium market — higher prices than most MENA. Fast-track if FDA/EMA approved. Dubai Healthcare City is Free Zone.',
  },
  {
    id: 'moph_qa',
    name: 'MOPH',
    country: 'Qatar',
    flag: '🇶🇦',
    color: '#8A1538',
    region: 'MENA',
    fullName: 'Ministry of Public Health - Pharmacy & Drug Control',
    avgApproval: '6-12 mo',
    cost: 'QAR 10-50K',
    difficulty: 2,
    marketSize: '$1.5B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '6-12 mo', docs: ['CTD', 'GMP cert', 'CPP', 'Stability', 'Local agent agreement'], tips: 'Relatively straightforward. Accepts GCC centralized registration. Fast-track for approved in 2+ GCC countries.' },
    ],
    keyContacts: [{ name: 'MOPH Pharmacy Dept', role: 'Registration', how: 'moph.gov.qa' }],
    foreignTips: 'Small but wealthy market. High per-capita spending. Local agent required.',
  },
  {
    id: 'nhra_bh',
    name: 'NHRA',
    country: 'Bahrain',
    flag: '🇧🇭',
    color: '#CE1126',
    region: 'MENA',
    fullName: 'National Health Regulatory Authority',
    avgApproval: '6-9 mo',
    cost: 'BHD 1-5K',
    difficulty: 2,
    marketSize: '$0.5B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '6-9 mo', docs: ['CTD', 'GMP', 'CPP', 'Stability'], tips: 'Fast and relatively easy. GCC mutual recognition. Good entry point for GCC market.' },
    ],
    keyContacts: [{ name: 'NHRA', role: 'Drug regulation', how: 'nhra.bh' }],
    foreignTips: 'Very accessible. Low fees. GCC gateway.',
  },
  {
    id: 'moh_kw',
    name: 'MOH-Kuwait',
    country: 'Kuwait',
    flag: '🇰🇼',
    color: '#007A3D',
    region: 'MENA',
    fullName: 'Ministry of Health - Drug & Food Control',
    avgApproval: '12-18 mo',
    cost: 'KWD 5-15K',
    difficulty: 2,
    marketSize: '$2B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '12-18 mo', docs: ['CTD', 'GMP cert', 'CPP', 'Stability', 'Samples'], tips: 'Can be slow. Accepts GCC registration. Government procurement dominant.' },
    ],
    keyContacts: [{ name: 'MOH Drug Control', role: 'Registration', how: 'moh.gov.kw' }],
    foreignTips: 'Government procurement via Central Medical Stores. Local agent required.',
  },
  {
    id: 'moh_om',
    name: 'MOH-Oman',
    country: 'Oman',
    flag: '🇴🇲',
    color: '#DB161B',
    region: 'MENA',
    fullName: 'Ministry of Health - Directorate General of Pharmaceutical Affairs',
    avgApproval: '6-12 mo',
    cost: 'OMR 1-5K',
    difficulty: 2,
    marketSize: '$1B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '6-12 mo', docs: ['CTD', 'GMP', 'CPP', 'Stability Zone IVa'], tips: 'Accepts GCC centralized. Moderate speed.' },
    ],
    keyContacts: [{ name: 'DGPA', role: 'Drug regulation', how: 'moh.gov.om' }],
    foreignTips: 'Growing market. Local agent required. GCC mutual recognition helps.',
  },
  {
    id: 'edqm_eg',
    name: 'EDA',
    country: 'Egypt',
    flag: '🇪🇬',
    color: '#C8102E',
    region: 'MENA',
    fullName: 'Egyptian Drug Authority',
    avgApproval: '12-24 mo',
    cost: 'EGP 50-200K',
    difficulty: 3,
    marketSize: '$8B',
    steps: [
      { phase: 'Reg', title: 'Drug Registration', dur: '12-24 mo', docs: ['CTD', 'GMP cert', 'CPP', 'Bioequivalence (generics)', 'Stability Zone IVb'], tips: 'EDA reformed in 2020 — modernizing. Priority for essential medicines. Large population = large market.' },
      { phase: 'Price', title: 'Pricing & Market', dur: '2-4 mo', docs: ['Price committee submission'], tips: 'Government controls pricing. Large public procurement. Population 105M+.' },
    ],
    keyContacts: [{ name: 'EDA', role: 'Drug regulation', how: 'edaegypt.gov.eg' }],
    foreignTips: 'Largest MENA population (105M+). Zone IVb stability. Arabic labeling. Local agent. Strong generics manufacturing base.',
  },
  {
    id: 'dmp_ma',
    name: 'DMP',
    country: 'Morocco',
    flag: '🇲🇦',
    color: '#006233',
    region: 'MENA',
    fullName: 'Direction du Médicament et de la Pharmacie',
    avgApproval: '12-18 mo',
    cost: 'MAD 20-80K',
    difficulty: 2,
    marketSize: '$2.5B',
    steps: [
      { phase: 'AMM', title: 'Marketing Authorization (AMM)', dur: '12-18 mo', docs: ['CTD (French)', 'GMP cert', 'CPP', 'Stability', 'BE study (generics)'], tips: 'French-language dossier. Morocco has strong local pharma industry. Francophone advantage for Algeria.' },
    ],
    keyContacts: [{ name: 'DMP', role: 'Drug regulation', how: 'sante.gov.ma' }],
    foreignTips: 'Francophone — language advantage for Algeria. Strong local industry (Sothema, Pharma5). Arabic + French labeling. Free trade agreements.',
  },
  {
    id: 'dpm_tn',
    name: 'DPM',
    country: 'Tunisia',
    flag: '🇹🇳',
    color: '#E70013',
    region: 'MENA',
    fullName: 'Direction de la Pharmacie et du Médicament',
    avgApproval: '12-18 mo',
    cost: 'TND 5-20K',
    difficulty: 2,
    marketSize: '$1.5B',
    steps: [
      { phase: 'AMM', title: 'Marketing Authorization', dur: '12-18 mo', docs: ['CTD French', 'GMP', 'CPP', 'Stability'], tips: 'French-language. Good cross-border opportunities with Algeria.' },
    ],
    keyContacts: [{ name: 'DPM', role: 'Drug regulation', how: 'santetunisie.rns.tn' }],
    foreignTips: 'Neighbor — easiest market for Algerian companies. French dossier. Similar regulatory culture. Cross-border supply chain.',
  },
  {
    id: 'sahpra',
    name: 'SAHPRA',
    country: 'South Africa',
    flag: '🇿🇦',
    color: '#007749',
    region: 'Africa',
    fullName: 'SA Health Products Regulatory Authority',
    avgApproval: '12-24 mo',
    cost: 'ZAR 50-200K',
    difficulty: 2,
    marketSize: '$8B',
    steps: [
      { phase: 'App', title: 'Registration Application', dur: '12-24 mo', docs: ['CTD', 'GMP (PIC/S or WHO)', 'Stability Zone IVa (30°C/65% RH)'], tips: 'Reliance on FDA/EMA/TGA. ZAZIBONA for multi-country Southern Africa. WHO collaborative registration.' },
    ],
    keyContacts: [
      { name: 'SAHPRA', role: 'Registration', how: 'sahpra.org.za' },
      { name: 'WHO PQ', role: 'Prequalification', how: 'prequal@who.int' },
    ],
    foreignTips: 'WHO PQ very valuable for African procurement. ZAZIBONA procedure for multiple SADC countries. Gateway to Sub-Saharan Africa.',
  },
  {
    id: 'nafdac',
    name: 'NAFDAC',
    country: 'Nigeria',
    flag: '🇳🇬',
    color: '#008751',
    region: 'Africa',
    fullName: 'National Agency for Food & Drug Administration & Control',
    avgApproval: '12-18 mo',
    cost: 'NGN 500K-2M',
    difficulty: 2,
    marketSize: '$4B',
    steps: [
      { phase: 'Reg', title: 'Registration', dur: '12-18 mo', docs: ['CTD', 'GMP cert', 'CPP', 'Stability', 'WHO PQ (preferred)'], tips: 'Nigeria is largest African pharma market. Population 220M+. WHO PQ accelerates review.' },
    ],
    keyContacts: [{ name: 'NAFDAC', role: 'Drug regulation', how: 'nafdac.gov.ng' }],
    foreignTips: 'Largest African market by population. WHO PQ strongly recommended. Local agent required. English labeling.',
  },
  {
    id: 'ppb',
    name: 'PPB',
    country: 'Kenya',
    flag: '🇰🇪',
    color: '#006600',
    region: 'Africa',
    fullName: 'Pharmacy & Poisons Board',
    avgApproval: '12 mo',
    cost: 'KES 50-200K',
    difficulty: 2,
    marketSize: '$1.5B',
    steps: [
      { phase: 'Reg', title: 'Registration', dur: '12 mo', docs: ['CTD', 'GMP (WHO/PIC/S)', 'CPP', 'Stability Zone IVa'], tips: 'East Africa hub. EAC harmonization with Uganda, Tanzania, Rwanda, Burundi.' },
    ],
    keyContacts: [{ name: 'PPB', role: 'Registration', how: 'pharmacyboardkenya.org' }],
    foreignTips: 'EAC harmonized registration for East Africa. WHO PQ valued. English labeling. Growing market.',
  },
  {
    id: 'fmhaca',
    name: 'FMHACA',
    country: 'Ethiopia',
    flag: '🇪🇹',
    color: '#078930',
    region: 'Africa',
    fullName: 'Food, Medicine and Healthcare Administration',
    avgApproval: '12-18 mo',
    cost: 'Low',
    difficulty: 2,
    marketSize: '$1B',
    steps: [
      { phase: 'Reg', title: 'Registration', dur: '12-18 mo', docs: ['CTD', 'GMP', 'CPP', 'Stability'], tips: 'Population 120M+. Growing pharma market. Government prioritizes essential medicines.' },
    ],
    keyContacts: [{ name: 'FMHACA', role: 'Regulation', how: 'fmhaca.gov.et' }],
    foreignTips: 'Second-largest African population. Growing market. Essential medicines focus.',
  },
  {
    id: 'fdb',
    name: 'FDA-Ghana',
    country: 'Ghana',
    flag: '🇬🇭',
    color: '#006B3F',
    region: 'Africa',
    fullName: 'Food and Drugs Authority',
    avgApproval: '6-12 mo',
    cost: 'GHS 10-50K',
    difficulty: 2,
    marketSize: '$0.8B',
    steps: [
      { phase: 'Reg', title: 'Registration', dur: '6-12 mo', docs: ['CTD', 'GMP', 'CPP', 'Stability'], tips: 'WHO PQ accelerates. ECOWAS harmonization. Relatively fast process.' },
    ],
    keyContacts: [{ name: 'FDA-Ghana', role: 'Registration', how: 'fdaghana.gov.gh' }],
    foreignTips: 'ECOWAS gateway for West Africa. WHO PQ valued. English labeling.',
  },
]
