-- Insert Pharmacies for Jijel, Algiers, and Oran
-- First, we need to get the user IDs from the auth.users table for the pharmacy accounts

-- Pharmacy 1 - Jijel
INSERT INTO pharmacies (
  id,
  user_id,
  name,
  name_ar,
  address,
  address_ar,
  city,
  wilaya_code,
  phone,
  email,
  latitude,
  longitude,
  is_active,
  is_verified,
  is_24h,
  is_on_duty,
  has_delivery,
  license_number,
  rating,
  review_count,
  working_hours,
  created_at,
  updated_at
)
SELECT 
  gen_random_uuid(),
  id,
  'Pharmacie El Moustakbel',
  'صيدلية المستقبل',
  '15 Rue Bachir El Ibrahimi, Jijel Centre',
  'شارع بشير الإبراهيمي 15، جيجل الوسط',
  'Jijel',
  '18',
  '034-47-12-34',
  'pharmacy1@algeriamed.test',
  36.8201,
  5.7667,
  true,
  true,
  false,
  true,
  true,
  'PH-JIJEL-2024-001',
  4.7,
  0,
  '{
    "monday": {"open": "08:00", "close": "20:00", "closed": false},
    "tuesday": {"open": "08:00", "close": "20:00", "closed": false},
    "wednesday": {"open": "08:00", "close": "20:00", "closed": false},
    "thursday": {"open": "08:00", "close": "20:00", "closed": false},
    "friday": {"open": "08:00", "close": "19:00", "closed": false},
    "saturday": {"open": "08:00", "close": "20:00", "closed": false},
    "sunday": {"open": "09:00", "close": "13:00", "closed": false}
  }'::jsonb,
  now(),
  now()
FROM auth.users WHERE email = 'pharmacy1@algeriamed.test';

-- Pharmacy 2 - Algiers
INSERT INTO pharmacies (
  id,
  user_id,
  name,
  name_ar,
  address,
  address_ar,
  city,
  wilaya_code,
  phone,
  email,
  latitude,
  longitude,
  is_active,
  is_verified,
  is_24h,
  is_on_duty,
  has_delivery,
  license_number,
  rating,
  review_count,
  working_hours,
  created_at,
  updated_at
)
SELECT 
  gen_random_uuid(),
  id,
  'Pharmacie Hydra Centrale',
  'صيدلية حيدرة المركزية',
  '42 Avenue des Frères Bouadou, Hydra, Alger',
  'شارع الإخوة بوعدو 42، حيدرة، الجزائر',
  'Alger',
  '16',
  '023-48-55-66',
  'pharmacy2@algeriamed.test',
  36.7538,
  3.0588,
  true,
  true,
  true,
  false,
  true,
  'PH-ALGER-2024-105',
  4.8,
  0,
  '{
    "monday": {"open": "00:00", "close": "23:59", "closed": false},
    "tuesday": {"open": "00:00", "close": "23:59", "closed": false},
    "wednesday": {"open": "00:00", "close": "23:59", "closed": false},
    "thursday": {"open": "00:00", "close": "23:59", "closed": false},
    "friday": {"open": "00:00", "close": "23:59", "closed": false},
    "saturday": {"open": "00:00", "close": "23:59", "closed": false},
    "sunday": {"open": "00:00", "close": "23:59", "closed": false}
  }'::jsonb,
  now(),
  now()
FROM auth.users WHERE email = 'pharmacy2@algeriamed.test';

-- Pharmacy 3 - Oran
INSERT INTO pharmacies (
  id,
  user_id,
  name,
  name_ar,
  address,
  address_ar,
  city,
  wilaya_code,
  phone,
  email,
  latitude,
  longitude,
  is_active,
  is_verified,
  is_24h,
  is_on_duty,
  has_delivery,
  license_number,
  rating,
  review_count,
  working_hours,
  created_at,
  updated_at
)
SELECT 
  gen_random_uuid(),
  id,
  'Pharmacie Es-Salam',
  'صيدلية السلام',
  '78 Boulevard Maata Mohamed, Oran Centre',
  'شارع معتة محمد 78، وهران الوسط',
  'Oran',
  '31',
  '041-39-22-11',
  'pharmacy3@algeriamed.test',
  35.6976,
  -0.6337,
  true,
  true,
  false,
  true,
  true,
  'PH-ORAN-2024-234',
  4.6,
  0,
  '{
    "monday": {"open": "08:00", "close": "21:00", "closed": false},
    "tuesday": {"open": "08:00", "close": "21:00", "closed": false},
    "wednesday": {"open": "08:00", "close": "21:00", "closed": false},
    "thursday": {"open": "08:00", "close": "21:00", "closed": false},
    "friday": {"open": "08:00", "close": "20:00", "closed": false},
    "saturday": {"open": "08:00", "close": "21:00", "closed": false},
    "sunday": {"open": "09:00", "close": "14:00", "closed": false}
  }'::jsonb,
  now(),
  now()
FROM auth.users WHERE email = 'pharmacy3@algeriamed.test';

-- Pharmacy 4 - Jijel
INSERT INTO pharmacies (
  id,
  user_id,
  name,
  name_ar,
  address,
  address_ar,
  city,
  wilaya_code,
  phone,
  email,
  latitude,
  longitude,
  is_active,
  is_verified,
  is_24h,
  is_on_duty,
  has_delivery,
  license_number,
  rating,
  review_count,
  working_hours,
  created_at,
  updated_at
)
SELECT 
  gen_random_uuid(),
  id,
  'Pharmacie Ibn Sina',
  'صيدلية ابن سينا',
  '23 Rue Emir Abdelkader, El Milia, Jijel',
  'شارع الأمير عبد القادر 23، الميلية، جيجل',
  'Jijel',
  '18',
  '034-41-88-99',
  'pharmacy4@algeriamed.test',
  36.7563,
  6.2658,
  true,
  true,
  false,
  false,
  true,
  'PH-JIJEL-2024-002',
  4.5,
  0,
  '{
    "monday": {"open": "08:00", "close": "19:00", "closed": false},
    "tuesday": {"open": "08:00", "close": "19:00", "closed": false},
    "wednesday": {"open": "08:00", "close": "19:00", "closed": false},
    "thursday": {"open": "08:00", "close": "19:00", "closed": false},
    "friday": {"open": "08:00", "close": "18:00", "closed": false},
    "saturday": {"open": "08:00", "close": "19:00", "closed": false},
    "sunday": {"open": "09:00", "close": "12:00", "closed": false}
  }'::jsonb,
  now(),
  now()
FROM auth.users WHERE email = 'pharmacy4@algeriamed.test';

-- Pharmacy 5 - Algiers
INSERT INTO pharmacies (
  id,
  user_id,
  name,
  name_ar,
  address,
  address_ar,
  city,
  wilaya_code,
  phone,
  email,
  latitude,
  longitude,
  is_active,
  is_verified,
  is_24h,
  is_on_duty,
  has_delivery,
  license_number,
  rating,
  review_count,
  working_hours,
  created_at,
  updated_at
)
SELECT 
  gen_random_uuid(),
  id,
  'Pharmacie Kouba Moderne',
  'صيدلية القبة الحديثة',
  '156 Rue Hassiba Ben Bouali, Kouba, Alger',
  'شارع حسيبة بن بوعلي 156، القبة، الجزائر',
  'Alger',
  '16',
  '023-75-33-44',
  'pharmacy5@algeriamed.test',
  36.7272,
  3.0916,
  true,
  true,
  false,
  true,
  true,
  'PH-ALGER-2024-106',
  4.9,
  0,
  '{
    "monday": {"open": "07:30", "close": "22:00", "closed": false},
    "tuesday": {"open": "07:30", "close": "22:00", "closed": false},
    "wednesday": {"open": "07:30", "close": "22:00", "closed": false},
    "thursday": {"open": "07:30", "close": "22:00", "closed": false},
    "friday": {"open": "07:30", "close": "21:00", "closed": false},
    "saturday": {"open": "07:30", "close": "22:00", "closed": false},
    "sunday": {"open": "08:00", "close": "13:00", "closed": false}
  }'::jsonb,
  now(),
  now()
FROM auth.users WHERE email = 'pharmacy5@algeriamed.test';

COMMIT;
